import { spawnSync } from "node:child_process";
import { createHash } from "node:crypto";
import {
  cpSync, existsSync, mkdirSync, readFileSync, readdirSync,
  renameSync, rmSync, writeFileSync,
} from "node:fs";
import path from "node:path";
import { setTimeout as delay } from "node:timers/promises";
import { fileURLToPath } from "node:url";

const root = fileURLToPath(new URL("../", import.meta.url));
const application = path.join(root, "apps", "yuansays-words");
const generated = path.join(application, ".output", "public");
const publicDirectory = path.join(root, "public");
const destination = path.join(publicDirectory, "words");
// Keep preparation outside public so a dev-server watcher cannot hold the
// staging directory open while Windows attempts the final rename.
const staging = path.join(root, "outputs", "words-build-staging");
const legacyStaging = path.join(publicDirectory, ".words-staging");
const argumentsList = process.argv.slice(2);
if (argumentsList.some((argument) => argument !== "--stage-only") || argumentsList.length > 1) {
  throw new Error("Usage: node scripts/build-words.mjs [--stage-only]");
}
// Internal recovery/verification path after an explicitly successful generate.
// Normal build commands always regenerate; this is not an automatic build cache.
const stageOnly = argumentsList.includes("--stage-only");

function includeAsset(source) {
  const relative = path.relative(generated, source).split(path.sep).join("/");
  return !/^(?:_redirects|_headers|robots\.txt|service-worker\.js|dicts\/en\/article(?:\/|$)|sound\/article(?:\/|$)|list\/(?:article|recommend_article)\.json|imgs\/(?:articles\.png|mini\.png|weixin\.png|zhifubao\.png|channel(?:\/|$)|covers(?:\/|$)|share\/qr\.png)|libs\/(?:51|lafiveone|s|t)\.js)$/.test(relative)
    && !/^(?:dicts\/en\/article|sound\/article|imgs\/channel|imgs\/covers)\//.test(relative);
}

function collectFiles(directory, prefix = "") {
  return readdirSync(directory, { withFileTypes: true }).flatMap((entry) => {
    const relative = `${prefix}${entry.name}`;
    return entry.isDirectory()
      ? collectFiles(path.join(directory, entry.name), `${relative}/`)
      : [relative];
  });
}

function writeOfflineWorker(directory) {
  const files = collectFiles(directory).filter((relative) =>
    relative === "index.html" ||
    /^_nuxt\/.+\.(?:js|mjs|json|css|woff2?|ttf|otf)$/.test(relative) ||
    /^(?:list\/(?:word|recommend_word)\.json|dicts\/en\/word\/CET4_T\.json)$/.test(relative) ||
    /^libs\/.+\.(?:js|mjs)$/.test(relative) ||
    /^sound\/.+\.(?:mp3|wav|ogg)$/.test(relative) ||
    /^(?:favicon\.(?:ico|svg)|imgs\/empty\.svg)$/.test(relative),
  ).sort();
  const hash = createHash("sha256");
  let totalBytes = 0;
  for (const relative of files) {
    const content = readFileSync(path.join(directory, relative));
    totalBytes += content.length;
    hash.update(relative).update(content);
  }
  const version = hash.digest("hex").slice(0, 16);
  const urls = files.map((relative) => relative === "index.html"
    ? "/words/"
    : `/words/${relative.split("/").map(encodeURIComponent).join("/")}`);
  const source = `// Generated by scripts/build-words.mjs. Scoped to yuansays words only.
const BASE = '/words/';
const CACHE_PREFIX = 'yuansays-words-';
const CACHE = CACHE_PREFIX + '${version}';
const PRECACHE = ${JSON.stringify(urls)};

self.addEventListener('install', (event) => {
  event.waitUntil(caches.open(CACHE).then((cache) => cache.addAll(PRECACHE)));
});

self.addEventListener('activate', (event) => {
  event.waitUntil((async () => {
    const keys = await caches.keys();
    await Promise.all(keys.filter((key) => key.startsWith(CACHE_PREFIX) && key !== CACHE)
      .map((key) => caches.delete(key)));
    await self.clients.claim();
  })());
});

self.addEventListener('fetch', (event) => {
  const request = event.request;
  const url = new URL(request.url);
  if (request.method !== 'GET' || url.origin !== self.location.origin || !url.pathname.startsWith(BASE)) return;
  if (url.pathname === BASE + 'service-worker.js') return;

  const isNavigation = request.mode === 'navigate'
    && !/\\.[^/]+\\/?$/.test(url.pathname)
    && !/^\\/words\\/(?:_nuxt|dicts|list|imgs|sound|libs)\\//.test(url.pathname);
  if (isNavigation) {
    event.respondWith((async () => {
      try {
        const response = await fetch(request);
        if (response.ok) return response;
      } catch { /* A cached shell can still open the local study data. */ }
      return await caches.match(BASE, { cacheName: CACHE })
        || new Response('Offline. Open yuansays words online once to prepare offline study.', {
          status: 503, headers: { 'Content-Type': 'text/plain; charset=utf-8' },
        });
    })());
    return;
  }

  if (/^\\/words\\/(?:_nuxt|dicts|list|imgs|sound|libs)\\//.test(url.pathname)
      || /^\\/words\\/favicon\\.(?:ico|svg)$/.test(url.pathname)) {
    event.respondWith((async () => {
      const cache = await caches.open(CACHE);
      const cached = await cache.match(request);
      if (cached) return cached;
      const response = await fetch(request);
      if (response.ok && response.type !== 'opaque') await cache.put(request, response.clone());
      return response;
    })());
  }
});
`;
  writeFileSync(path.join(directory, "service-worker.js"), source);
  console.log(`Prepared offline cache ${version}: ${files.length} local assets, ${(totalBytes / 1024 / 1024).toFixed(2)} MiB before transfer compression.`);
}

// These exact directories contain generated assets only. Keep deletion restricted
// to their exact, resolved paths even when this script runs from another cwd.
function removeGeneratedDirectory(directory) {
  const resolved = path.resolve(directory);
  const allowed = [destination, staging, legacyStaging].map((entry) => path.resolve(entry));
  if (!allowed.includes(resolved)) {
    throw new Error(`Refusing to remove an unexpected directory: ${resolved}`);
  }
  rmSync(resolved, { recursive: true, force: true, maxRetries: 5, retryDelay: 200 });
}

async function publishStagedAssets() {
  const retryable = new Set(["EPERM", "EBUSY", "EACCES", "ENOTEMPTY", "EEXIST"]);
  removeGeneratedDirectory(destination);
  for (let attempt = 0; attempt < 5; attempt += 1) {
    try {
      renameSync(staging, destination);
      return;
    } catch (error) {
      if (!retryable.has(error.code)) throw error;
      if (attempt < 4) await delay(200 * (attempt + 1));
    }
  }

  // Antivirus and directory watchers can forbid a rename while allowing file
  // reads. A failed copy still fails the build; never publish a partial tree.
  console.warn("Staging rename remained busy; copying verified generated assets instead.");
  removeGeneratedDirectory(destination);
  cpSync(staging, destination, { recursive: true, force: false, errorOnExist: true });
  const expected = collectFiles(staging).sort();
  const actual = collectFiles(destination).sort();
  if (JSON.stringify(expected) !== JSON.stringify(actual) || expected.some((relative) =>
    !readFileSync(path.join(staging, relative)).equals(readFileSync(path.join(destination, relative))),
  )) {
    throw new Error("Copied word assets did not match staging; build stopped before publication.");
  }
  try {
    removeGeneratedDirectory(staging);
  } catch (error) {
    // outputs is excluded from hosting, so a locked staging copy can safely be
    // retained for cleanup on the next build after verification has succeeded.
    if (!retryable.has(error.code)) throw error;
    console.warn(`Verified assets staged; temporary outputs directory remains busy (${error.code}).`);
  }
}

if (!stageOnly) {
  if (!existsSync(path.join(application, "node_modules", "nuxt", "package.json"))) {
    console.log("Installing yuansays words dependencies from its pinned lockfile…");
    const install = process.platform === "win32"
      ? spawnSync(process.env.ComSpec || "cmd.exe", ["/d", "/s", "/c", "npx.cmd --yes pnpm@10.33.0 install --frozen-lockfile --prod=false"], {
          cwd: application, stdio: "inherit", windowsHide: true,
        })
      : spawnSync("npx", ["--yes", "pnpm@10.33.0", "install", "--frozen-lockfile", "--prod=false"], {
          cwd: application, stdio: "inherit",
        });
    if (install.error) throw install.error;
    if (install.status !== 0) process.exit(install.status ?? 1);
    if (!existsSync(path.join(application, "node_modules", "nuxt", "package.json"))) {
      throw new Error("Dependency installation finished without Nuxt.");
    }
  }

  console.log("Building yuansays words for /words/…");
  // Nuxt auto-detects Cloudflare Pages in CI and otherwise emits dist/words.
  // The parent Next.js export stages the provider-neutral .output/public tree.
  // Windows .cmd files require cmd.exe; the command is a fixed string, with no
  // paths or user-controlled arguments interpolated into shell syntax.
  const result = process.platform === "win32"
    ? spawnSync(process.env.ComSpec || "cmd.exe", ["/d", "/s", "/c", "node_modules\\.bin\\nuxt.cmd generate --preset=static"], {
        cwd: application,
        env: { ...process.env, NUXT_APP_BASE_URL: "/words/" },
        stdio: "inherit",
        windowsHide: true,
      })
    : spawnSync(path.join(application, "node_modules", ".bin", "nuxt"), ["generate", "--preset=static"], {
        cwd: application,
        env: { ...process.env, NUXT_APP_BASE_URL: "/words/" },
        stdio: "inherit",
      });

  if (result.error) throw result.error;
  if (result.status !== 0) process.exit(result.status ?? 1);
} else {
  console.log("Staging the existing successful Nuxt generation; source freshness is the caller's responsibility.");
}
if (!existsSync(path.join(generated, "index.html"))) {
  throw new Error("Nuxt generation finished without .output/public/index.html.");
}

mkdirSync(publicDirectory, { recursive: true });
removeGeneratedDirectory(legacyStaging);
removeGeneratedDirectory(staging);
mkdirSync(path.dirname(staging), { recursive: true });
cpSync(generated, staging, { recursive: true, filter: includeAsset });
writeOfflineWorker(staging);
await publishStagedAssets();
console.log("Staged yuansays words in public/words.");
